### ISSUE TITLE
Cannot test the typings

### ISSUE THREAD

**Issue by szmarczak** [szmarczak/cacheable-lookup#11]
See https://github.com/SamVerschueren/tsd/issues/57

This can be solved via converting this project to TypeScript. Feel free to pick this up.

**Comment by sindresorhus** [comment]
Why not just put the typings in root for now?

**Comment by szmarczak** [comment]
Hmm... That would fix this. But I'm not a fan of putting things in the root directory.

**Comment by szmarczak** [comment]
3ea3ee9f9e2fd7f2ec26ffff4fc26598d8e92769
