### ISSUE TITLE
set dns.lookup family by this._iface(has4 and has6)

### ISSUE THREAD

**Issue by my1229** [szmarczak/cacheable-lookup#38]
https://github.com/szmarczak/cacheable-lookup/blob/5960e1d98c61f9edd6873eb03050a12122f24af4/source/index.js#L285

could we set family by this._iface(has4 and has6), not set 0 always.

**Comment by szmarczak** [comment]
If you want to override the `family` option, then definitely a no. If you want to specify the family, then you can just set the `family` option when calling `lookup(...)`.

**Comment by my1229** [comment]
yes, override is not a good idea, but it seems that setting options.family also does not take effect when calling dns.lookup(...) interface，actually it is used to filter ip in package.

**Comment by szmarczak** [comment]
It must be something wrong on your side, it works correctly here.
