### ISSUE TITLE
What are the breaking changes for version 6.0.0

### ISSUE THREAD

**Issue by cata0309** [szmarczak/cacheable-lookup#39]

**Comment by cata0309** [comment]
Hello! I noticed the release of version 6.0.0, the release log doesn't seem to provide a description about what the breaking changes might be.

**Comment by szmarczak** [comment]
There is description in the release log:

https://github.com/szmarczak/cacheable-lookup/releases

> Fix #36 (Allow fallbackDuration = 0 without disabling fallback) 41f6229

It isn't necessarily breaking, but might have the potential of unexpected action due to behavior change.
