### ISSUE TITLE
Failure with Node v16.5.0

### ISSUE THREAD

**Issue by thurisaz** [szmarczak/cacheable-lookup#46]
ModuleNotFoundError: Module not found: Error: Can't resolve 'dns' in '/Users/myuser/code/myproject/node_modules/cacheable-lookup/source'

Trying to install dns, etc manually results in 

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'dns@0.2.2',
npm WARN EBADENGINE   required: { node: '>= 0.10.0 < 0.11.0' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hawk@0.10.2',
npm WARN EBADENGINE   required: { node: '0.8.x' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hoek@0.7.6',
npm WARN EBADENGINE   required: { node: '0.8.x' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tomahawk@0.1.6',
npm WARN EBADENGINE   required: { node: '>= 0.8.0 < 0.11.0' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }

Does this module work with my version of node?

**Comment by szmarczak** [comment]
You must be doing something wrong. `dns` is a native Node.js module.
