### ISSUE TITLE
Error while working with got + electron.

### ISSUE THREAD

**Issue by kingbotss** [szmarczak/cacheable-lookup#47]
![image](https://user-images.githubusercontent.com/80538787/134552688-5a220876-5618-4298-8a5d-f4fb8cc54076.png)
**
If I remove this module from got. it shows no error. but taking too long to make requests.
**

**What is the root cause?**

I am using node LTS 14 LATEST & TRIED 16.10. SAME ERROR.

**Comment by kingbotss** [comment]
https://github.com/sindresorhus/got/issues/1875

**Comment by szmarczak** [comment]
We don't support Electron.
