### ISSUE TITLE
Consider bumping `keyv`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [szmarczak/cacheable-lookup#5]
To `keyv@4` so `got` can dedupe the version it uses.

**Comment by szmarczak** [comment]
Thanks for the heads up, released `0.2.2` 😄

**Comment by Kikobeats** [comment]
hey @szmarczak, I noted keyv was removed but it's still present at TypeScript types:

https://github.com/szmarczak/cacheable-lookup/blob/master/index.d.ts#L1

BTW, why keyv was removed? now is not possible to persist the results 😢

**Comment by Kikobeats** [comment]
I think should be trivial support keyv just exposing a way to customize the internal cache (like `opts.cache`)

https://github.com/szmarczak/cacheable-lookup/blob/master/source/index.js#L97

**Comment by szmarczak** [comment]
Temporary workaround: `cacheable._cache = keyvInstance;`

> just exposing a way to customize the internal cache (like opts.cache)

What do you mean by `customize`? If you mean `sync`, then you will lose the benefit of high performance.

**Comment by szmarczak** [comment]
You shouldn't sync the DNS cache as this is machine-dependent.

**Comment by wtgtybhertgeghgtwtg** [comment]
> then you will lose the benefit of high performance.

While [the speed-up from dropping `keyv`](https://github.com/szmarczak/cacheable-lookup/commit/557a724b305dac4363462fccb8b5332185ed8d9a#diff-04c6e90faac2675aa89e2176d2eec7d8L174-R186) is really, really, really, **_really_** impressive, for [the given use cases](https://github.com/szmarczak/cacheable-lookup#usage), it's hard to picture a scenario where performance here is a bottleneck.

**Comment by szmarczak** [comment]
> it's hard to picture a scenario where performance here is a bottleneck

Even if the performance was 1 op/s there would be no bottleneck (unless you use all of Node.js available resources). Just the requests would be delayed. The point is to save that milliseconds. When you make 1M it will sum up to tens of minutes or maybe even hours.

**Comment by szmarczak** [comment]
I'll revert back the `options.cache` removal.

**Comment by Kikobeats** [comment]
> You shouldn't sync the DNS cache as this is machine-dependent.

Can you elaborate this?

**Comment by szmarczak** [comment]
Imagine you have several server locations, e.g. in the USA and in the UK. You query `google.com`. It's pointless to make all the requests to one specific location, because your local DNS provider will give you the nearset Google server to you.

**Comment by szmarczak** [comment]
Also `cacheable-lookup` supports the `hosts` file so you may want to have the same hosts file on all your machines.

**Comment by szmarczak** [comment]
I found a way to support Keyv without no performance drop if you use the native cache.

https://github.com/szmarczak/cacheable-lookup/compare/v4.0.1...master

@wtgtybhertgeghgtwtg @Kikobeats does this look good? Note that it doesn't install `keyv` by default, you have to install `keyv` on your own.

**Comment by wtgtybhertgeghgtwtg** [comment]
Looks good to me.  Thank you for your fast response and quick support.

**Comment by szmarczak** [comment]
No problem. Published `4.1.0`. Please let me know if there are any inconsistencies :D

**Comment by Kikobeats** [comment]
> Imagine you have several server locations, e.g. in the USA and in the UK. You query google.com. It's pointless to make all the requests to one specific location, because your local DNS provider will give you the nearset Google server to you.

There you're assuming servers are on different locations; if they are under the same location, sharing the cache can have the benefit to don't query resolver for something already resolved. Am I wrong?

**Comment by szmarczak** [comment]
>  if they are under the same location, sharing the cache can have the benefit to don't query resolver for something already resolved. Am I wrong?

You're actually right. A PR mentioning this use case in the readme is welcome :)

**Comment by Kikobeats** [comment]
@szmarczak 

Something to consider in order to use keyv is TTL is associated with the storage

https://github.com/lukechilds/keyv#optionsttl

Checking the code I can notice the equivalent value here is `maxTtl`

https://github.com/szmarczak/cacheable-lookup/compare/v4.0.1...master#diff-c60c67bd505d9618ebf77a7f130903d0R96

but isn't living on the storage, so I can be a wrong assumption since you need to setup your `maxTtl`, even you are using a custom storage with a fixed ttl.

**Comment by szmarczak** [comment]
> I can notice the equivalent value here is maxTtl

You notice it wrong, it's not the same.

**Comment by Kikobeats** [comment]
How different are they?

**Comment by szmarczak** [comment]
From the readmes:

> ##### options.maxTtl
> 
> Type: `number`<br>
> Default: `Infinity`
> 
> Limits the cache time (TTL in seconds).

> #### options.ttl
> 
> Type: `Number`<br>
> Default: `undefined`
> 
> Default TTL. Can be overridden by specififying a TTL on `.set()`.

There's no such thing as "default TTL" in `cacheable-lookup`.

**Comment by Kikobeats** [comment]
but it has a default value, right? https://github.com/szmarczak/cacheable-lookup/blob/master/source/index.js#L96

keyv is saying "default ttl" because you can override it on execution time, otherwise it fallbacks on the constructor (default) value

The thing is if you use a keyv store and pass it in this way:

```ks
const cache = new Keyv({ttl: 3000})
const cacheable = new CacheableLookup({ cache} );
```

Internally, `cacheable` ttl is `Infinity` while in the store the value is `300`.

**Comment by szmarczak** [comment]
> keyv is saying "default ttl" because you can override it on execution time

`cacheable-lookup` **always** passes TTL as the `cache.set` argument, therefore there's no such thing as "default TTL" here.

> Internally, cacheable ttl is Infinity while in the store the value is 300.

You still confuse these two, they are not the same. As I mentioned before, `keyv`'s TTL doesn't affect `cacheable`'s TTL. It's just that simple.

**Comment by Kikobeats** [comment]
> As I mentioned before, keyv's TTL doesn't affect cacheable's TTL. It's just that simple.

That's the thing, even a cache store is provided, the ttl will be no respected!

**Comment by szmarczak** [comment]
> That's the thing, even a cache store is provided, the ttl will be no respected!

What? `cacheable-lookup` respects the TTL and I have tests proving that. 

You still don't understand how Keyv works. GitHub is not a place for tutoring.
