### ISSUE TITLE
Question: How is DNS resolved?

### ISSUE THREAD

**Issue by curlyblueeagle** [szmarczak/cacheable-lookup#53]
Sorry if this seems like a basic question, but how does `cacheable-lookup` resolve DNS? Looking at the code it seems to be using `dns.resolve` with `dns.lookup` as a fallback. Am I correct in this assumption?

**Comment by szmarczak** [comment]
Correct. It uses `dns.lookup` as a fallback in order to support `/etc/hosts`.

**Comment by curlyblueeagle** [comment]
Perfect thank you! This answers my question, so I will close issue.
