### ISSUE TITLE
round-robin dns support 

### ISSUE THREAD

**Issue by link89** [szmarczak/cacheable-lookup#56]
It seems like `cacheable-lookup` doesn't support round-robin DNS. Is there any options to support it?

**Comment by szmarczak** [comment]
https://github.com/szmarczak/cacheable-lookup/pull/57#issuecomment-1176681555

If you insist on doing this, you can simply wrap `lookup` with `{all: true}` and simply do your own logic.

**Comment by link89** [comment]
That will have to change the implementation of request, which is what I try to avoid.
