### ISSUE TITLE
Ability to set minTtl?

### ISSUE THREAD

**Issue by timtucker-dte** [szmarczak/cacheable-lookup#60]
As best as I can tell, the app code uses the minimum of the TTL value on the DNS record or the maxTtl to decide how long records should be cached.

Is there any way to set a minimum TTL value?

One of the hosts that we look up has a TTL set to only 10 seconds, but we want to ensure that values are cached for longer than that.

**Comment by ewwink** [comment]
sorry to ask, I don't understand why minTtl is considered an anti-pattern but maxTtl is not.
the reason user use cache app is the ability to set any TTL.
