### ISSUE TITLE
http2 & cacheable-lookup

### ISSUE THREAD

**Issue by phawxby** [szmarczak/cacheable-lookup#72]
It seems that `cacheable.install()` should probably work with the http2 agent from https://github.com/szmarczak/http2-wrapper.

Currently it emits the TS error.
```
Type 'Agent' is missing the following properties from type 'Agent': maxFreeSockets, maxSockets, maxTotalSockets, freeSockets, and 2 more.
```

I think it should work if the typings to `install()` were a bit more relaxed as to what they consider to be an agent and leave `verifyAgent` to decide if install is possible.

**Comment by szmarczak** [comment]
By reading the source code, it expects HTTP/1 Agents. I don't think it's a good idea to support HTTP/2 Agents for now (no official HTTP/2 session management api), it would be best to pass this as [a `lookup` option](https://github.com/szmarczak/cacheable-lookup#using-the-lookup-option).
