### ISSUE TITLE
Source isn't returned in Entry object

### ISSUE THREAD

**Issue by purplecandy** [szmarczak/cacheable-lookup#73]
I'm on the latest version 7.0.0 and the lookup code is this but on the master branch  the code has support for source as well. 

Maybe you should publish another version
![image](https://user-images.githubusercontent.com/17525936/198006709-3b1fbfb2-df80-4c0d-9f6f-e29e6b6c1b8f.png)

**Comment by szmarczak** [comment]
Are you sure you're on 7.0.0?

![image](https://user-images.githubusercontent.com/36894700/198036026-bc986188-dabe-49d0-a8fa-4408112effd7.png)
